apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: pr
    control-plane: pr-controller
  name: pr-system
---
apiVersion: v1
imagePullSecrets:
- name: pr-pull-secret
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: pr
  name: pr-controller-manager
  namespace: pr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: pr
  name: pr-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: pr-controller-manager
  namespace: pr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/instance: manager-workloads-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: pr
  name: pr-manager-workloads-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supply-chain-workloads
subjects:
- kind: ServiceAccount
  name: pr-controller-manager
  namespace: pr-system
---
apiVersion: v1
data:
  .dockerconfigjson: e30K
kind: Secret
metadata:
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/instance: pull-secret
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: secret
    app.kubernetes.io/part-of: pr
  name: pr-pull-secret
  namespace: pr-system
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: pr-controller
  namespace: pr-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: pr-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/instance: pr-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: pr
    control-plane: pr-controller
  name: pr-controller-manager
  namespace: pr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: pr-controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        control-plane: pr-controller
    spec:
      containers:
      - args:
        - run
        - --bind-address
        - 0.0.0.0
        env:
        - name: GITLAB_SHARED_SECRET
          valueFrom:
            secretKeyRef:
              key: shared-secret
              name: pr-gitlab-secret
        - name: GITHUB_SHARED_SECRET
          valueFrom:
            secretKeyRef:
              key: shared-secret
              name: pr-github-secret
        image: controller:latest
        name: controller
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: pr-controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: pr-proxy
  namespace: pr-system
spec:
  routes:
  - services:
    - name: pr-controller
      port: 8080
  virtualhost:
    fqdn: pr.internal.testenv.co.uk
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: pr-github-secret
  namespace: pr-system
spec:
  length: 64
  secretTemplate:
    stringData:
      shared-secret: $(value)
    type: Opaque
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: pr-gitlab-secret
  namespace: pr-system
spec:
  length: 64
  secretTemplate:
    stringData:
      shared-secret: $(value)
    type: Opaque
