apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: gitlab-secret
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      shared-secret: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: github-secret
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      shared-secret: $(value)