---
apiVersion: v1
kind: Namespace
metadata:
  name: pr-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-controller
  namespace: pr-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pr-controller
  template:
    metadata:
      labels:
        app: pr-controller
    spec:
      containers:
      - name: pr-controller
        image: garethjevans/pr-controller:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: pr-controller
        args:
          - run
          - --bind-address
          - 0.0.0.0
          - --document-root
          - /storage
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
          - mountPath: /storage
            name: storage
      volumes:
        - name: storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pr-controller
  namespace: pr-controller
spec:
  selector:
    app: pr-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: pr-controller
