---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-workloads-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/part-of: pr
    app.kubernetes.io/managed-by: kustomize
  name: manager-workloads-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supply-chain-workloads
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-workloads-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pr
    app.kubernetes.io/part-of: pr
    app.kubernetes.io/managed-by: kustomize
  name: manager-supply-chains
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supply-chains
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
