---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - example.com
  resources:
  - examples
  - examplepullrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch